build:
  maxIssues: 0

style:
  MagicNumber:
    active: false
  ReturnCount:
    active: false

complexity:
  LongParameterList:
    active: true
    functionThreshold: 8
    constructorThreshold: 10

comments:
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true
  UndocumentedPublicProperty:
    active: false
